/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { ClientDTO } from '.';

export type RoomLanguage = 'en' | 'de';

export interface JoinRoomDTO {
  password?: string;
  playerName: string;
  roomID: string;
}

export interface RoomConfigurationDTO {
  language: RoomLanguage;
  name: string;
  password?: string;
  victoryThreshold: number;
}

export interface RoomDTO {
  clientCount: number;
  clients: ClientDTO[];
  createdAt: Date;
  hasPassword: boolean;
  language: RoomLanguage;
  name: string;
  victoryThreshold: number;
}
